use_frameworks!

platform :ios, '9.0'

target 'MCopManager_Example' do
  pod 'MCopManager', :path => '../'

  target 'MCopManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
